# Generated by Django 3.2.6 on 2021-08-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20210818_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'AguasCalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Coahuila'), (6, 'Colima'), (7, 'Chiapas'), (8, 'Chihuahua'), (9, 'Distrito Federal'), (10, 'Durango'), (11, 'Guanajuato'), (12, 'Guerrero'), (13, 'Hidalgo'), (14, 'Jalisco'), (15, 'México'), (16, 'Michoacán'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo León'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Querétaro'), (23, 'Quintana Roo'), (24, 'San Luis Potosí'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatán'), (32, 'Zacatecas')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='algas',
            name='colonia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='algas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='algas',
            name='localidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='polen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=200)),
                ('nombre_comun', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('numero_recolecta', models.IntegerField()),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='imagenes/')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.familia')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=200)),
                ('nombre_comun', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('numero_recolecta', models.IntegerField()),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='imagenes/')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.familia')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='hongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=200)),
                ('nombre_comun', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('numero_recolecta', models.IntegerField()),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='imagenes/')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.familia')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='helecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=200)),
                ('nombre_comun', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('numero_recolecta', models.IntegerField()),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='imagenes/')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.familia')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='frutosemilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=200)),
                ('nombre_comun', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('numero_recolecta', models.IntegerField()),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='imagenes/')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.familia')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
