# Generated by Django 3.2.6 on 2021-08-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20210818_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='algas',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.municipio'),
        ),
        migrations.AlterField(
            model_name='algas',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='alga'),
        ),
        migrations.AlterField(
            model_name='frutosemilla',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='frutosemilla'),
        ),
        migrations.AlterField(
            model_name='helecho',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='helecho'),
        ),
        migrations.AlterField(
            model_name='hongo',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='hongo'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='planta'),
        ),
        migrations.AlterField(
            model_name='polen',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='polen'),
        ),
    ]
