# Generated by Django 3.2.6 on 2021-08-19 21:19

import apps.catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20210819_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Algas',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=apps.catalogo.models.Algas.get_upload_path_imagen),
        ),
    ]
