# Generated by Django 3.2.6 on 2021-09-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20210910_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algas',
            name='familia',
        ),
        migrations.AddField(
            model_name='algas',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie'),
        ),
    ]
