# Generated by Django 3.2.6 on 2021-09-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20210910_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frutosemilla',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='helecho',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='hongo',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='polen',
            name='familia',
        ),
        migrations.AddField(
            model_name='frutosemilla',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie'),
        ),
        migrations.AddField(
            model_name='frutosemilla',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Hermafrodita')], null=True),
        ),
        migrations.AddField(
            model_name='helecho',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie'),
        ),
        migrations.AddField(
            model_name='helecho',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Hermafrodita')], null=True),
        ),
        migrations.AddField(
            model_name='hongo',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie'),
        ),
        migrations.AddField(
            model_name='hongo',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Hermafrodita')], null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie'),
        ),
        migrations.AddField(
            model_name='planta',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Hermafrodita')], null=True),
        ),
        migrations.AddField(
            model_name='polen',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie'),
        ),
        migrations.AddField(
            model_name='polen',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Hermafrodita')], null=True),
        ),
    ]
