# Generated by Django 3.2.6 on 2021-09-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_auto_20210910_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='algas',
            name='nombre_colector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='frutosemilla',
            name='nombre_colector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helecho',
            name='nombre_colector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hongo',
            name='nombre_colector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='nombre_colector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='polen',
            name='nombre_colector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
