# Generated by Django 3.2.6 on 2021-09-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_auto_20210910_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polen',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie'),
        ),
    ]
