# Generated by Django 3.2.6 on 2021-09-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20210915_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={},
        ),
    ]
