# Generated by Django 3.2.6 on 2021-09-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_alter_planta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'default_permissions': ()},
        ),
    ]
