# Generated by Django 3.2.6 on 2021-09-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_alter_planta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='frutosemilla',
            name='latitud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frutosemilla',
            name='longitud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
