# Generated by Django 3.2.6 on 2021-10-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_auto_20210930_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frutosemilla',
            name='latitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frutosemilla',
            name='longitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
