# Generated by Django 3.2.6 on 2021-10-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_auto_20211011_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='latitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='longitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
