# Generated by Django 3.2.6 on 2021-10-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_auto_20211013_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='algas',
            name='latitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='algas',
            name='longitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
