# Generated by Django 3.2.6 on 2021-10-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_auto_20211013_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='helecho',
            name='latitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='helecho',
            name='longitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hongo',
            name='latitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hongo',
            name='longitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polen',
            name='latitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polen',
            name='longitud',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
